[build]
  command = "npm ci && npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"

[build.processing.secrets]
  SECRETS_SCAN_OMIT_KEYS = "NODE_ENV,PORT"
  SECRETS_SCAN_OMIT_PATHS = "README.md,desc.md,package.json,dist/**,attached_assets/**"


[context.deploy-preview.environment]
  NODE_ENV = "development"